# cpack part include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "mupro.software")
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The MuPRO SDK library")
# set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/mupro/${PROJECT_VERSION_MAJOR}")
# set(CPACK_PACKAGE_INSTALL_DIRECTORY
#     "sdk/mupro/${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MIONR}")

# set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
# set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
# set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION})

set(CPACK_PACKAGE_CONTACT "support@muprosoftware.com")
# set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Xiaoxing Cheng")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

# set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT) set(CPACK_COMPONENTS_GROUPING
# ALL_COMPONENTS_IN_ONE) set(CPACK_DEB_COMPONENT_INSTALL YES)

set(CPACK_STRIP_FILES YES)
# set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE ON)

include(CPack)
